### PR TITLE
Travis CI supports Rails Girls Summer of Code 2015

### PR DESCRIPTION
**Pull request by svenfuchs**
/cc @carlad @rkh @anikalindtner

### CODE REVIEW

**Comment by anikalindtner** [comment]
love the blog post! gret work, @carlad! <3  just a question about the last quote: where did you chose that from? Also: maybe we have better one? I'm fine with using it, if we don't, but I'd love to see if we can come up with something better than "i care about this because my mom/sister/daughter".

**Comment by svenfuchs** [comment]
@anikalindtner it's from the 2014 sponsors page, from agileanimal

**Comment by carlad** [comment]
I like the quote. I think the personal importance of the people you care about is a strong way to appeal to the same sentiments in others. I'm more likely to donate to a cause my brother runs in a marathon for, because I care about what he cares about. What about the quote don't you like?

**Comment by anikalindtner** [comment]
@carlad I also like it, it's just a bit generic, since you hear that all the time. And a bit sad, that some men only come round to supporting these great initiavtives after they get a daughter. 

they even included it in the ally bingo ;)


 That's all. I was just wondering if we might have an even better (a.k.a. more original) one. But if not, I'm totally fine with using it.

**Comment by carlad** [comment]
Copy that. Although I disagree that it's not original. I think it's totally original, because it's heartfelt and personal. It's how he truly feels. He's not supporting the cause because it's hip or fashionable or cliched - he's supporting it because he can identify with his daughter and wants to make a difference if he can. 

I guess I relate to his feelings regarding family as I think the reason I support equality for women in tech has a lot to do with what I saw in my extended, extremely patriarchal Sicilian family. Of all the worthy issues in the world I could devote my time to I choose this one because it resonates on a personal level. And I think appealing to this in potential donors is more powerful than a quote that's perhaps not so personal. 

I also think it's a bit harsh to judge the donor, and that he has only come around because he has a daughter. I don't know the guy personally, but he donated a lot out of his own pocket and, well, I think whatever the motivation it's good to be generous in return ;-)

Anyway, I'm not sure there are any other quotes that are as powerful, but let me know if you find any.

**Comment by anikalindtner** [comment]
I get that! It's just one of the more critical points I have out of my day-to-day dealing with the world, my gender studies/feminist background. So I can get a bit exhausted/critical/cynical sometimes. But I agree that probably loads and loads of people can rely and personally I think it's quite cute what he wrote. 

" think whatever the motivation it's good to be generous in return ;-)" :D true. No, i actually haven't found a better quote, but I thought I want to give github a chance of getting space in our blogpost, since they are partners already. 

So I'd say, let's give GH a chance to say something, other than that: GO! <3

**Comment by carlad** [comment]
:thumbsup;

**Pull request merged**
